#specify version of docker
version: '3'
services:
  echo-service:
    build: .
    ports:
      - "5000:5000"
    restart: always

  redis-server:
    image: 'redis'
    ports:
      - "6379:6379"